CREATE TABLE public.users (
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  roles text[] NOT NULL,
  createdAt DATE NOT NULL DEFAULT CURRENT_DATE,
  updatedAt DATE NOT NULL DEFAULT CURRENT_DATE
);
