# Generated by Django 5.2.8 on 2025-12-31 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='orderId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.order'),
        ),
    ]
